### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by Kraznys** [AstoriaCore/Astoria-ClasslessSystem#3]
Hi i have a problem i am missing mana, energy and rage bar. I  followed instruction the installation where is the problem please? The rest works well.

**Comment by AstoriaCore** [comment]
You can just use the addon from AscensionWoW. We deactivated the Bars at some point since we wanted to introduce a Blizzlike way to show these Powers. :)

**Comment by Kraznys** [comment]
Where can i find these addons please? I searched everywhere. I even downloaded WoW ascension and I didn't find any addon. I want to ask if it is compatible with TrinityCore please. I tried it and I can't use rage spells or energy spells because I don't have a resource like rage and energy or mana, so I ask. thank you and have a nice day.
